# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/python/black.git
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v2.2.3
    hooks:
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/PyCQA/flake8
    rev: 3.7.8
    hooks:
      - id: flake8
        args: ['--config=setup.cfg']
        types: [python]
        additional_dependencies:
          - flake8>=3.7.8
          - flake8-black
          - black==21.12b0 # the last version that supports Python 2
        language_version: python3
