- job:
    name: jjb-tox-cross-python-jenkins
    description: Tests compatibility with master branch of python-jenkins
    parent: tox-py27
    required-projects:
      - openstack/python-jenkins
      - openstack-infra/jenkins-job-builder
    voting: true

- project:
    templates:
      - openstack-python37-jobs-nonvoting
      - openstack-python36-jobs
    check:
      jobs:
        - jjb-tox-cross-python-jenkins
        - openstack-tox-linters
        - openstack-tox-py27
    gate:
      jobs:
        - openstack-tox-linters
        - openstack-tox-py27
