- job:
    name: jjb-tox-cross-python-jenkins
    description: Tests compatibility with master branch of python-jenkins
    parent: tox-py27
    required-projects:
      - jjb/python-jenkins
      - jjb/jenkins-job-builder
    voting: true

- job:
    name: jjb-tox-docs-linkcheck
    parent: tox
    vars:
      tox_envlist: docs-linkcheck

- project:
    check:
      jobs:
        - jjb-tox-cross-python-jenkins
        - jjb-tox-docs-linkcheck
